### ISSUE TITLE
Increase font version per build

### ISSUE THREAD

**Issue by onovotny** [adam7/delugia-code#13]
The current version of the font 1910.040. It might be worth adding a third value (1910.040.x) to the font so that Windows will update the font when you install them. It's not clear what the current behavior is (does an install update or ignore) and it's hard to confirm that anything changed.

**Comment by Finii** [comment]
On my machine (Windows 10 1809) it asks me if it shall update:
![Selection_244](https://user-images.githubusercontent.com/16012374/67393540-e3fc9880-f5a2-11e9-9768-e8d116d82960.png)

Anyhow, an additional information about the patch time would be nice.

**Comment by onovotny** [comment]
I don't know what kind of info is allowed but a git commit hash & current time would be nice as well.

**Comment by Finii** [comment]
Fonts have a 'comment' and 'fontlog' field fro these types of information, but I don't know if Windows shows them. I will try.
Also noticed that we clear the 'copyright' field (because that was what adam7 did and I just fixed it so that it works), but actually we are not allowed to by licensing rules. So that is a pending PR anyhow.
