### ISSUE TITLE
v2105.24.1 and up are slightly more stretched on vertical axis

### ISSUE THREAD

**Issue by LuanVSO** [adam7/delugia-code#61]
these are both Delugia complete v2105.24.2 (right):
![image](https://user-images.githubusercontent.com/43626415/124214435-94d16f80-dac8-11eb-8f41-3dc55ef90426.png) ![image](https://user-images.githubusercontent.com/43626415/124214641-ebd74480-dac8-11eb-8fa7-25ddc62e842e.png)
now cascadia code (left) and delugia v2105.24.2 (right):
![image](https://user-images.githubusercontent.com/43626415/124214907-6607c900-dac9-11eb-976b-e79561e7e0e9.png) ![image](https://user-images.githubusercontent.com/43626415/124214802-32c53a00-dac9-11eb-8088-a5973101355a.png)

**Comment by Finii** [comment]
Hej Luan,

I can not reproduce. It put some fonts next to each other in _Writer_, in separate Columns (where they can have individual line heights):

![image](https://user-images.githubusercontent.com/16012374/124224747-899d3480-db06-11eb-96f3-5ed15280b6a2.png)

The font files I used are:
* `ttf/CascadiaCode.ttf` _2105.24_
* `ttf/CascadiaCodePL.ttf` _2105.24_
* `DelugiaBook.ttf` _2105.24.2_
* `DelugiaComplete.ttf` _2105.24.2_

Having a closer look at your images I assume you have accidentally swapped them. Anyhow, here are both images with some added lines at 250%:

_Your bottom image:_
![s2](https://user-images.githubusercontent.com/16012374/124226611-aedf7200-db09-11eb-8476-1740bd7eaacb.png)

All looks fine.

_Your top image:_
![s1](https://user-images.githubusercontent.com/16012374/124226735-ddf5e380-db09-11eb-87a9-c101aa10649d.png)

Here I shifted the right part (where the vertical dashed blue line is) up by 2 pixels.
The vertical height is identical in both fonts, just Terminal seems to start the right font (Delugia?) a bit higher in the window?

My conclusion from this examination is:
* Its not vertically stretched, line heights are identical (in both your images and in my test)
* Delugia seems to have a initial vertical offset of 2px in _Terminal_ but not in _Writer_

Is this what you mean?

**Comment by Finii** [comment]
In fact there is even no 2px shift. I already had it in the image above...:

![image](https://user-images.githubusercontent.com/16012374/124227564-2d88df00-db0b-11eb-8d9f-7b3fab575a8b.png)

**After** the shift the window title is of same height, so what you did is just shift one of the windows.

I see no difference here at all. Please reopen if you still believe there is a problem and can show some conclusive images,
Thank you for filing the issue, though :-)

**Comment by Finii** [comment]
Had another look...

I believe now I know what you mean:
![image](https://user-images.githubusercontent.com/16012374/124228677-d1bf5580-db0c-11eb-8292-80191f95ab80.png)

**Comment by Finii** [comment]
I still can not reproduce with _Writer_:
![image](https://user-images.githubusercontent.com/16012374/124229044-4d210700-db0d-11eb-80be-556f11657f09.png)

Capital-height is the same here.

Now in the Gnome Terminal:

Cascadia:
![Screenshot from 2021-07-02 08-20-22](https://user-images.githubusercontent.com/16012374/124231119-27e1c800-db10-11eb-9479-1151aa7019b7.png)

Delugia:
![Screenshot from 2021-07-02 08-20-12](https://user-images.githubusercontent.com/16012374/124231147-30d29980-db10-11eb-8068-d18727141358.png)

Looks a bit different, escp Delugia's **bold** is less bold. But then, I do not have _Delugia Bold_ installed, so it is autogenerated, while it is embedded in the Cascadia font file.

Having a closer look:

![image](https://user-images.githubusercontent.com/16012374/124231015-08e33600-db10-11eb-8a1c-fc668c3fb745.png)

Yes, the capital height is different! (slightly)

**Comment by Finii** [comment]
Ah ha!

Now I used `ttf/static/CascadiaCodePL-Regular.ttf`, and its height is identical to `DelugiaComplete.ttf`:

![c2_1](https://user-images.githubusercontent.com/16012374/124234136-f1a64780-db13-11eb-8fca-9193fbb0b702.png)

![c2_2](https://user-images.githubusercontent.com/16012374/124234153-f7039200-db13-11eb-9278-f52d0e739b48.png)

Here a magnified view:

![image](https://user-images.githubusercontent.com/16012374/124234190-01259080-db14-11eb-8a2b-302efde32abf.png)

----
## Conclusion:

So **there is a capital height difference** between the all-in-one `CascadiaCodePL.ttf` and the Microsoft supplied static version `CascadiaCodePL-Regular.ttf`

Delugia is based on the static Cascadia Code font, and there is no height difference between the two.
Delugia up to `v2105.24` based on the dynamic `CascadiaCodePL.ttf` font.

The switch to the static fonts has been necessary because we can not patch in all the other glyphs while keeping the font dynamic. Read 'can not' as would require considerable amounts of time.

I believe one can live with the slightly different height rendering. Different... Well, this is Delugia and it renders as high as Delugia renders ;-)

**Comment by trallnag** [comment]
Just to add to this: The type designer of Cascadia is also saying that the static versions of Cascadia differ quite strongly from the variable TTF versions
