### ISSUE TITLE
[Question]: how to get the italic fontface look like in readme?

### ISSUE THREAD

**Issue by younger-1** [adam7/delugia-code#73]
I installed the latest release of delugia and delugia-book. In my system, it looks like:
![a](https://user-images.githubusercontent.com/45989017/153586169-412a0312-9847-43e3-a396-0c3a719f5be0.png)

But in readme, the displayed italic fontface have different appearance.

![b](https://github.com/adam7/delugia-code/raw/master/delugia_book.png)

How can I get the italic fontface look like in readme?

**Comment by Finii** [comment]
You mean the small Ell (`l`) ?

There was something, let me check.

Please tell if you means something else.

**Comment by Finii** [comment]
'Curly' italic is in OpenType Stylistic Set 1:

![image](https://user-images.githubusercontent.com/16012374/153598941-192cad64-281a-4083-a6a4-43f4583eca55.png)

You need to activate that (SS1).

This is the case since [Cascadia Code revision 2106.17](https://github.com/microsoft/cascadia-code/releases/tag/v2106.17)

![image](https://user-images.githubusercontent.com/16012374/153599282-58d687d2-187c-4639-acc9-b4cc6c84b7cb.png)

**Remark:**
I know, most applications are not able to give you all features in an OpenType font, so in your application it may not be selectable. Sorry we can not do anything about it.
Some of the fonts I use have nice swashes, and with Ubuntu the only thing that seems to support them is `Scribus`... sigh. On Windows the last time I looked (which is some years ago) the MS equivalent of `Impress` was not even able to do it (what is is called? Power something). On Windows the only thing that worked was MS Publisher or so?
But then, I read somewhere else, that VisualCode does support OpenType stuff, and one can select that. Not checked.

Any hints on applications that utilize all OpenType features are welcome.

**Comment by Finii** [comment]
See https://github.com/microsoft/cascadia-code/issues/468 and https://github.com/microsoft/cascadia-code/issues/503

Obviously Sublime Text can also handle OpenType features:
![image](https://user-images.githubusercontent.com/16012374/153602081-3965e860-c684-4edd-b71c-39b49565c6e2.png)

**Comment by younger-1** [comment]
Thanks very much.

**Comment by younger-1** [comment]
I was originly looking for stylistic set support for alacritty which is far away complete https://github.com/alacritty/alacritty/issues/3166 And vscode support stylistic set by configuring `editor.fontLigatures`. 

![图片](https://user-images.githubusercontent.com/45989017/153608997-21f8910c-0212-48c3-a7d4-b9fe41c8e999.png)

To my surprise, windows terminal recently added support for both stylistic set and font axes which support disable rules.
![图片](https://user-images.githubusercontent.com/45989017/153610583-a26840cd-eb9f-430b-9c1f-12b38f223c72.png)

**Comment by Finii** [comment]
Hooray :-)

And I also learned of https://github.com/twardoch/fonttools-opentype-feature-freezer

So you can just so something along these lines
```shell
$ pip install --upgrade opentype-feature-freezer
$ pyftfeatfreeze -f ss01 -S -U Curly ~/.local/share/fonts/DelugiaComplete-Italic.ttf.featfreeze.otf DelugiaCurlyComplete-Regular.otf
```
or omit `-S -U Curly` and replace the normal `-Italic` file.

Works effortlessly:

![image](https://user-images.githubusercontent.com/16012374/153614781-9ea15101-2ba0-48a0-aedd-9e18889a1dc3.png)

**Comment by Finii** [comment]
_Thinking: Hmm, vertical stuff being really vertical on slanted font?? WTF?_

![image](https://user-images.githubusercontent.com/16012374/153615475-9c754a53-6f52-4bf2-bac1-39d0aea76f08.png)

**Comment by younger-1** [comment]
> _Thinking: Hmm, vertical stuff being really vertical on slanted font?? WTF?_
😂so strange vertical bar, beyond my comprehension

**Comment by kenmcd** [comment]
> Thinking: Hmm, vertical stuff being really vertical on slanted font?? WTF?

**Italic version: make the vertical pipe character actually vertical #507** 
https://github.com/microsoft/cascadia-code/issues/507
