### ISSUE TITLE
Add codicons symbols (and/or more?)

### ISSUE THREAD

**Issue by registerGen** [adam7/delugia-code#75]
Thank you for this awesome project! It would be great if we can add more symbols.

https://github.com/adam7/delugia-code/blob/a16ac8c0f35e6143b10edaa2d01e5fe7e64adcb3/.github/workflows/ci.yaml#L82

ryanoasis/nerd-fonts@96ab7f6ef7ab5cb8f949696f96d5c4d2c39c5061

According to the above two links, `font-patcher` used in this repo is older than the one which has support for codicons. So why not use the latest version in order to get more symbols?

**Comment by Finii** [comment]
You are of course right. The problem was/is that `font-patcher` still has some defects that we fix here.

Some fixes are already backported to Nerd Fonts, but some other fixes are still pending over there (https://github.com/ryanoasis/nerd-fonts/pull/723).

I guess after 723 there is almost no difference anymore between `Delugia` and `Cascaydia Cove`.

The patched fonts after 723 can be found for example here: https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode

I think 723 should/will go into Nerd Font v2.2.0, and then we can simply use that here.

**Comment by Finii** [comment]
Fixed via #77
