### ISSUE TITLE
Update font when nerd fonts updated

### ISSUE THREAD

**Issue by latipun7** [adam7/delugia-code#76]
As I understand, this font updated when new cascadia code updated. But, when new nerd fonts updated with its added icons and bug fixes, this font not updated, just waiting for new cascadia code.

Please support updating font for the most updated cascadia code and nerd fonts.

Thank you.

**Comment by Finii** [comment]
Well, the last Nerd Fonts updates just brought the features we have here to Nerd Fonts.
With `Caskaydia Cove 2.2.2` I guess it is en par with `Delugia`.

Delugia has been the driver, the test bed of the new Nerd Font features; but that means Delugia uses a modified patching process. You are right we should get rid of that (see also #75).

And I can work only on one project at a time :grimacing: but in principle you are right.
Just getting out `2.2.0` and the bugfix releases over there took an extreme amount of time.

**Comment by trallnag** [comment]
> With Caskaydia Cove 2.2.2 I guess it is en par with Delugia.

Is it though? Comparing I am still seeing a difference

Caskaydia Cove latest version

![3](https://user-images.githubusercontent.com/24834206/192368076-25e15482-f088-4899-87bb-1f8d580df149.png)

Delugia Book latest version

![4](https://user-images.githubusercontent.com/24834206/192368122-d35e65f0-3fc0-4a78-bfe6-a26a2c6c1d3c.png)

**Comment by Finii** [comment]
Hmm, I just found 4 commits in my local repo, that are not here :sob: 
Too long done nothing. Can't remember...

![image](https://user-images.githubusercontent.com/16012374/192449640-2d4e50c9-aa7b-4095-a1fa-c57ffc4771b5.png)

**Comment by Finii** [comment]
> > With Caskaydia Cove 2.2.2 I guess it is en par with Delugia.
> 
> Is it though? Comparing I am still seeing a difference

That might be the here-missing PPEM fix https://github.com/ryanoasis/nerd-fonts/pull/761

![image](https://user-images.githubusercontent.com/16012374/192599035-719098dd-f3ed-47b3-a5d9-4df6a9581274.png)
_From the CI run here_

**Comment by Finii** [comment]
@latipun7 @trallnag Maybe you want to / can check Delugia after the update.

The artifacts can be downloaded here:
https://github.com/adam7/delugia-code/actions/runs/3137726398

**Comment by trallnag** [comment]
I checked and there is still a difference. In the Windows font preview I noticed that Delugia has "TrueType Outlines" while Caskaydia uses "PostScript Outlines".

![caskaydia](https://user-images.githubusercontent.com/24834206/192609119-1441af2c-1649-49fc-82ab-e5ac3d49916b.png)

![delugia](https://user-images.githubusercontent.com/24834206/192609125-eaeac78e-3ff9-481f-988b-30bfa5dbe823.png)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24834206/192610053-b275ac75-1b03-46ad-94fe-b5771ba40213.gif)

Failing to compare it properly with the original Cascadia because for that font way more weights are showing up in the preview. So it's difficult to overlay them.

Before I tested it in Windows Terminal and there I'm seeing other differences. Looking through the projects issues suggests that the font rendering in WT is not perfect.

**Comment by trallnag** [comment]
Here is the difference in Windows Terminal on font 9 with Clear Type:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24834206/192614619-2e6c3a3b-cff3-45b3-8b4b-32b87c416426.gif)

Anyway I don't want anyone to fix this or something like that. It is just interesting

**Comment by Finii** [comment]
Excellent report :+1:

> Anyway I don't want anyone to fix this or something like that. It is just interesting
> 
> Delugia certainly seems closer to the original in WT. But again, this could be due to WT rendering and look completely different in another app.

I guess you compare with `Cascadia Code TTF`? The `Caskaydia Cove` is `OTF`, which has more rendering information apart from the glyph shapes.

**Comment by Finii** [comment]
> Failing to compare it properly with the original Cascadia because for that font way more weights are showing up in the preview.

Probably you use the Variable Font version of Cascadia. You can think of that as the 'Regular' font but added mathematical routines to calculate other weights on the fly (by the rendering engine), so that there is only one set of outlines and not one set for each weight.

> Crazy and unexpected (to me) how complex non-bitmap fonts are.

Almost nothing is 'hard coded' in the fonts, there are sets on sets of instructions and rules one can put into the file; code to be executed on render time... Plus there are 3 major players (Apple, MS, Adobe) that have different opinions and implement their own 'sets' :grimacing: ... well it got better over the last years.
