### ISSUE TITLE
Default character height is greater than Cascadia Code

### ISSUE THREAD

**Issue by rashil2000** [adam7/delugia-code#78]
See the gif below, when I change the font to Delugia, the characters seem to become longer. It's not really a big deal, but it was noticeable to me at font size 11. (The gif has font size set to 32, to make the difference easily visible).

![cursor2](https://user-images.githubusercontent.com/46838874/215567477-78caeeb1-e020-4396-b585-a39f270a5f15.gif)

**Comment by Finii** [comment]
Thanks for reporting. Sorry to hear you have an issue.

I assume you use the `Cascadia Code VF`, which is hard-bundled with `Windows Terminal`?
There are slight differences between the VF and the static versions, even the unpatched fonts.

Or do you have the static `Cascadia Code` version(s) installed? Then I would have a look.

**Comment by rashil2000** [comment]
Yes, I'm using the Cascadia Code that is bundled with Windows Terminal (Preview).

**Comment by Finii** [comment]
Ok, I tried to normal (non preview) version, and it uses the ttf-VF:

![image](https://user-images.githubusercontent.com/16012374/215757671-5f258130-a294-480d-9454-eba79815ad9b.png)

Lets see if we can see differences.

Download release from MS, compare `ttf` versions of static and VF:

![image](https://user-images.githubusercontent.com/16012374/215758579-2e8c3dd6-43d7-47ae-9bce-351a5a5c7c12.png)

The glyph is drawn a light bit differently, but the top-point on the exact same position: 604/1080.

Delugia is the same:

![image](https://user-images.githubusercontent.com/16012374/215759314-98e27e37-9605-4771-be16-3037ff7998fb.png)

Vertical metrics are also the same (except WIN values which should not be used because use-typo-metrics bit is set:

![image](https://user-images.githubusercontent.com/16012374/215760250-44b2618b-c50c-41e4-9dd8-e960635996b5.png)

Testing CascadiaCodeVL vs Delugia at 42pt:

![Peek 2023-01-31 13-42](https://user-images.githubusercontent.com/16012374/215762969-83ae87e3-fe5a-44f0-815a-cceb98a94d18.gif)

The difference is less than 1 pixel. Even with still bigger fonts, the difference is always < 1 px.
I believe this is a rendering issue.

I also noticed that `Caskaydia Cove` (the 'original' Nerd Fonts version of `Cascadia Code` has even more rendering problems, the antialiasing seems to be broken there? Ah, now that I write that, NF uses the `otf` versions. Hmm. There is devinitively somthing strange about how `Windows Terminal` handles `Cascadia Code` in the antialias, it looks far far smoother than all other fonts.

**Comment by Finii** [comment]
Unfortunately I have forgotten almost all Windows related things. Would be worth to try disabling ClearType (I believe it was called something like that) and or other font rendering settings. But were are they ;-D

**Comment by Finii** [comment]
The rendering flags are different :-o

![image](https://user-images.githubusercontent.com/16012374/215767230-b96f5a59-1023-4a5b-9fa0-39d7ffb4141d.png)

![image](https://user-images.githubusercontent.com/16012374/215768384-53ecb3e5-82af-4933-a992-7fee05f32410.png)

Is the code not working :-o

![image](https://user-images.githubusercontent.com/16012374/215768123-162729fd-036d-4da9-9626-8d3e1875b709.png)

**Comment by Finii** [comment]
WAT

![image](https://user-images.githubusercontent.com/16012374/215771678-897aabfe-2dd5-427a-9f58-23d07ffd2a1e.png)

Ah, now I know. Delugia pushes the patched font one time more through `fontforge` to change the names, and `fontforge` does not even see neither the flags nor the lowestPPEM, so they get destroyed afterwards :-(

Will fix that, thanks for reporting!

**Comment by Finii** [comment]
```python
#!/usr/bin/env sh
#
# Create and rename one font style according to the specs
#
# Example invocation:
#   do_generate 01 --powerline --mono CascadiaCodePL-Regular.ttf DelugiaPowerline.ttf Delugia Regular
#
# No parameters are checked, but they are:
# 1: Number of logfile
# 2: Conversion spec #1
# 3: Conversion spec #2
# 4: Input font file name
# 5: Output font file name
# 6: Font family name

set -e

if [ "$#" -ne 6 ]; then
    exit 1
fi

PWD=$( pwd )

rm -f C*.ttf
fontforge -script "${PWD}/font-patcher" --careful "${3}" --custom SomeExtraSymbols.sfd --no-progressbars "${PWD}/ttf/static/${4}" "${2}" --outputdir "${PWD}" | tee "process${1}.log"

if [ -z "${OURVERSION}" ]; then
    # Github CI sets this variable, but this can be useful for manual calls:
    OURVERSION=`git describe --always --tags`
fi
fontforge -script "${PWD}/rename-font" --orig "${PWD}/ttf/static/${4}" --input ${PWD}/C*.ttf --output "${PWD}/${5}" --version "${OURVERSION}" --name "${6}"
```

First patching, the patching fixes the flags and lowest-ppm AFTER `fontforge` did its thing.
And then again `fontforge` to change the names, but `fontforge` always writes dump default values in both fields :-(

**Comment by Finii** [comment]
![Peek 2023-01-31 16-28](https://user-images.githubusercontent.com/16012374/215803397-a0a7d1fa-08d7-4fe8-88e4-f2c451310921.gif)

Still some difference, but less visibly so

**Comment by Finii** [comment]
@rashil2000 

Maybe you can check the fonts generated with the fix (scroll down):
https://github.com/adam7/delugia-code/actions/runs/4062092045

If they are fine we can pull and re-release.

**Comment by rashil2000** [comment]
> There is devinitively somthing strange about how Windows Terminal handles Cascadia Code in the antialias, it looks far far smoother than all other fonts.

Yes damn you're right, I remember suddenly spotting this difference when I upgraded my Terminal version some months ago. I felt something changed with how the Terminal handles fonts, and waited for the next release. 

> Maybe you can check the fonts generated with the fix (scroll down):

I downloaded the artifact from the action. 

Here's Cascadia:
![image](https://user-images.githubusercontent.com/46838874/216009882-11d160da-e9a4-47c0-b017-22123396c09f.png)

Here's Delugia:
![image](https://user-images.githubusercontent.com/46838874/216009996-a69f198f-2b52-468e-b578-38e0b22fc841.png)

The font size is 11, unfortunately I still see the original difference.

**Comment by Finii** [comment]
So. Finally to be able to really test this, I removed the Cascadia Cove that are part of the Windows Terminal app.

Which is kind of hard
* gain access to C:/Programs/WindowsApps
* set youself as owner for `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.15.3466.0_x64__8wekyb3d8bbwe`
* set youself as owner for all 4 font files in that folder
* add full access right for `everyone` on the 4 fonts
* move the 4 fonts to another location (e.g. desktop) - deleting is impossible
* reboot
* enjoy to be able to install whichever Cascadia Code you like and use Windows Terminal with that

![grafik](https://user-images.githubusercontent.com/16012374/216594808-ad26c05e-b7b1-405a-b5bc-1291e8809a58.png)

_No Cascadia Code to be seen in neither Terminal nor Fonts_

**Comment by Finii** [comment]
Install only static fonts, the two we want to check:

![grafik](https://user-images.githubusercontent.com/16012374/216596923-86ca4b77-b3ee-43a0-89a8-9b5e4d8d2acc.png)

## Still different

![grafik](https://user-images.githubusercontent.com/16012374/216597198-f4e7484a-126e-4827-9bf9-56fd4706e78c.png)

![grafik](https://user-images.githubusercontent.com/16012374/216597258-7c8f2c42-09e7-4b25-8a4d-d8a32ae40317.png)

**Comment by Finii** [comment]
No wait, I compare the `ttf`` with the `otf`

![grafik](https://user-images.githubusercontent.com/16012374/216600558-d5b09e66-b1d9-4ea1-b849-dda256d53aa8.png)

![grafik](https://user-images.githubusercontent.com/16012374/216600651-2b73b582-5a8a-42ae-a766-28fb24676c04.png)

**Comment by Finii** [comment]
Ah, now they look the same...

![grafik](https://user-images.githubusercontent.com/16012374/216601252-b0906de3-4fb0-47dc-984a-19fb2782a54c.png)

_Right side: see the Cascadia Code `otf` is installed_

![grafik](https://user-images.githubusercontent.com/16012374/216601614-409cf638-d3f3-4a24-b25a-757069878618.png)

![grafik](https://user-images.githubusercontent.com/16012374/216601671-5079b6f5-9346-4853-92dd-0d12d175fe99.png)

**Comment by Finii** [comment]
The `otf` version has no `autohint` run, at least not in the version number.

**Comment by Finii** [comment]
![Peek 2023-02-03 13-28](https://user-images.githubusercontent.com/16012374/216603939-1d1f031f-e796-4cfb-9167-29e4e86aad54.gif)

So the issue you have is a difference between
`Cascadia Code` `otf` and `ttf`

I guess ;-)


AHH, but then you talk about `Delugia` which is a patched version of the `ttf` Cascadia Code one.

I do not know what they have in `Cascadia Code TTF` that is missing in `Cascadia Code OTF` and all patched versions.

**Comment by Finii** [comment]
Differently encoded in tables

![image](https://user-images.githubusercontent.com/16012374/216612545-89ab5278-18a6-49e9-8bdf-ced135fb7453.png)

**Comment by Finii** [comment]
Ah, so if I create a Delugia with the current HEAD `font-patcher` (HEAD of nerd-fonts) from the static/ttf, it will look different, but look the same as Cascadia Code static/ttf.

So there are differences in Cascadia Code depending on static/variable and ttf/otf, but we can do nothing about these.
The patched fonts (Delugia and also vanilla Caskaydia) look the same as the original MS font that has been taken as source.

![grafik](https://user-images.githubusercontent.com/16012374/216642293-1ee051b2-f896-4f08-95ee-af7fe4fcc772.png)

---

I would close this now. (?)

This (Delugia) should be more like the "normal / autoinstalled" Cascadia Code, because `Windows Terminal` installs the variable-ttf version.
Delugia is based on the static-ttf version.
CaskaydiaCove is based on static-otf which looks even more different.

**Comment by rashil2000** [comment]
Okay, thanks for the detailed investigation!
