### ISSUE TITLE
There are no icons for some commonly used files, such as word.

### ISSUE THREAD

**Issue by breakTBB** [adam7/delugia-code#87]
![image](https://github.com/user-attachments/assets/1c6e842e-678d-43be-89fb-093565da4dd6)

**Comment by breakTBB** [comment]
I changed the font from Delugia PL mono to Delugia, and now it works. Why is this happening? I thought PL was specially designed for powerline.

**Comment by Finii** [comment]
Taken from https://github.com/adam7/delugia-code#what-is-nerd-fonts-anyway

![image](https://github.com/user-attachments/assets/8d42a296-cf42-472d-ba5f-50092bdbc95f)

> I thought PL was specially designed for powerline.

Yes. Powerline is these fancy separators, in my case triangular-ish:

![image](https://github.com/user-attachments/assets/883d0d2b-3b19-4bf6-868d-a013a5fd8e70)

_Pure Powerline prompt, with lock-icon, branch-icon and special separators_

The PL font variant contains also some (very few) not Powerline related icons (Seti/Custom and Devicons).

But usually people want 'all the Nerd Font icons', and that is _Complete_.

Mono or not-Mono says if the icons are bigger or not. (Just mentioning because you said you switched from a Mono font to a Non-Mono one.) A description what `Mono` means can be found [here](https://github.com/ryanoasis/nerd-fonts/discussions/1103) at Nerd Fonts.

---

Edit:

Other example: My neovim with Powerline

![image](https://github.com/user-attachments/assets/554e6fbd-5a2f-4536-93d6-7bf76c06b5ca)

Note the Linux-Indicator uses a non Powerline icon, the Tux.
But special separators (for the 'tabs' on top and the triangular things in the status) and the git branch icon are Poweline icons.

**Comment by breakTBB** [comment]
> Taken from https://github.com/adam7/delugia-code#what-is-nerd-fonts-anyway
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/377355070-8d42a296-cf42-472d-ba5f-50092bdbc95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTk2MzgsIm5iZiI6MTcyOTIxOTMzOCwicGF0aCI6Ii8xNjAxMjM3NC8zNzczNTUwNzAtOGQ0MmEyOTYtY2Y0Mi00NzJkLWJhNWYtNTAwOTJiZGJjOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjllMDQzYjhkNWU4YzczNTZmNWM3Y2VmYjhiYTA0YzEzMzY1NDhmNjRjZDhjZTY3YjIwZjE0ZDIyYTg0NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xfE1aqfzKaJSna-pKENHs6A6-e0P5S8eSY8hgpHDqxM)
> 
> > I thought PL was specially designed for powerline.
> 
> Yes. Powerline is these fancy separators, in my case triangular-ish:
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/377355792-883d0d2b-3b19-4bf6-868d-a013a5fd8e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTk2MzgsIm5iZiI6MTcyOTIxOTMzOCwicGF0aCI6Ii8xNjAxMjM3NC8zNzczNTU3OTItODgzZDBkMmItM2IxOS00YmY2LTg2OGQtYTAxM2E1ZmQ4ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOWQ0MDg3NDY4OTVhZjBlMjkyZWNjNDBhYWMxZTg4MDliNzY4NzJiY2QwN2UxNGQxYzI0NDgzZjYwOWU3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K81wZ2dwUVRGAmez9s3nKCcSwF1dYTpUshEChRjX7X0)
> 
> _Pure Powerline prompt, with lock-icon, branch-icon and special separators_
> 
> The PL font variant contains also some (very few) not Powerline related icons (Seti/Custom and Devicons).
> 
> But usually people want 'all the Nerd Font icons', and that is _Complete_.
> 
> Mono or not-Mono says if the icons are bigger or not. (Just mentioning because you said you switched from a Mono font to a Non-Mono one.) A description what `Mono` means can be found [here](https://github.com/ryanoasis/nerd-fonts/discussions/1103) at Nerd Fonts.
> 
> Edit:
> 
> Other example: My neovim with Powerline
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/377358744-554e6fbd-5a2f-4536-93d6-7bf76c06b5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTk2MzgsIm5iZiI6MTcyOTIxOTMzOCwicGF0aCI6Ii8xNjAxMjM3NC8zNzczNTg3NDQtNTU0ZTZmYmQtNWEyZi00NTM2LTkzZDYtN2JmNzZjMDZiNWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAyNDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZDE5MjNhMzIyZTBlZTMyZGRhNjdmMzJkOGM1MWRlM2NhNGVkZDU3ZDJhMWU5MThmNDFmMDJlYzIxNGY3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WnpgFgjPpZarIecqDIze8pwRvqJ_b5wX5yT_wbDkWwc)
> 
> Note the Linux-Indicator uses a non Powerline icon, the Tux. But special separators (for the 'tabs' on top and the triangular things in the status) and the git branch icon are Poweline icons.

Thank you so much for such a detailed explanation.
